language: cpp

sudo: false

addons:
  apt:
    packages:
    - git
    - dpkg-dev
    - make
    - g++
    - gcc
    - binutils
    - libx11-dev
    - libxpm-dev
    - libxft-dev
    - libxext-dev
    - libbz2-dev
    - python-dev

install: true

script: 
  - ./GetToolDAQ.sh --b1
  - ./GetToolDAQ.sh --b2
  - ./GetToolDAQ.sh --b3
  - ./GetToolDAQ.sh --b4
  - source Setup.sh; ./GetToolDAQ.sh --b5

