sudo: false

language: cpp

compiler: gcc
dist: trusty

services:
  - docker

before_install:
  - docker pull anniesoft/toolanalysis:base

install:
  - docker run -v `pwd`:/root/buildtest anniesoft/toolanalysis:base /bin/sh -c " cd /root/buildtest ; ln -s /ToolAnalysis/ToolDAQ ./ToolDAQ ; make clean; make "

script:
  - docker run -v `pwd`:/root/buildtest anniesoft/toolanalysis:base /bin/sh -c " cd /root/buildtest ; ls; source ./Setup.sh ; ./Analyse "

notifications:
  email:
    recipients:
      - b.richards@qmul.ac.uk
    on_success: never # default: change
    on_failure: always # default: always

