#include <map>
#include <utility>
#include <string>

#include "Particle.h"

const std::map<int,std::string> Particle::pdgcodetoname{
	std::pair<int,std::string>{2212,"Proton"},
	std::pair<int,std::string>{-2212,"Anti Proton"},
	std::pair<int,std::string>{11,"Electron"},
	std::pair<int,std::string>{-11,"Positron"},
	std::pair<int,std::string>{12,"Electron Neutrino"},
	std::pair<int,std::string>{-12,"Anti Electron Neutrino"},
	std::pair<int,std::string>{22,"Gamma"},
	std::pair<int,std::string>{2112,"Neutron"},
	std::pair<int,std::string>{-2112,"Anti Neutron"},
	std::pair<int,std::string>{-13,"Muon+"},
	std::pair<int,std::string>{13,"Muon-"},
	std::pair<int,std::string>{130,"Kaonlong"},
	std::pair<int,std::string>{211,"Pion+"},
	std::pair<int,std::string>{-211,"Pion-"},
	std::pair<int,std::string>{321,"Kaon+"},
	std::pair<int,std::string>{-321,"Kaon-"},
	std::pair<int,std::string>{3122,"Lambda"},
	std::pair<int,std::string>{-3122,"Antilambda"},
	std::pair<int,std::string>{310,"Kaonshort"},
	std::pair<int,std::string>{3112,"Sigma-"},
	std::pair<int,std::string>{3222,"Sigma+"},
	std::pair<int,std::string>{3212,"Sigma0"},
	std::pair<int,std::string>{111,"Pion0"},
	std::pair<int,std::string>{311,"Kaon0"},
	std::pair<int,std::string>{-311,"Antikaon0"},
	std::pair<int,std::string>{14,"Muon Neutrino"},
	std::pair<int,std::string>{-14,"Anti Muon Neutrino"},
	std::pair<int,std::string>{-3222,"Anti Sigma-"},
	std::pair<int,std::string>{-3212,"Anti Sigma0"},
	std::pair<int,std::string>{-3112,"Anti Sigma+"},
	std::pair<int,std::string>{3322,"Xsi0"},
	std::pair<int,std::string>{-3322,"Anti Xsi0"},
	std::pair<int,std::string>{3312,"Xsi-"},
	std::pair<int,std::string>{-3312,"Xsi+"},
	std::pair<int,std::string>{3334,"Omega-"},
	std::pair<int,std::string>{-3334,"Omega+"},
	std::pair<int,std::string>{-15,"Tau+"},
	std::pair<int,std::string>{15,"Tau-"},
	std::pair<int,std::string>{100,"OpticalPhoton"},
	std::pair<int,std::string>{3328,"Alpha"},
	std::pair<int,std::string>{3329,"Deuteron"},
	std::pair<int,std::string>{3330,"Triton"},
	std::pair<int,std::string>{3351,"Li7"},
	std::pair<int,std::string>{3331,"C10"},
	std::pair<int,std::string>{3345,"B11"},
	std::pair<int,std::string>{3332,"C12"},
	std::pair<int,std::string>{3350,"C13"},
	std::pair<int,std::string>{3349,"N13"},
	std::pair<int,std::string>{3340,"N14"},
	std::pair<int,std::string>{3333,"N15"},
	std::pair<int,std::string>{3334,"N16"},
	std::pair<int,std::string>{3335,"O16"},
	std::pair<int,std::string>{3346,"Al27"},
	std::pair<int,std::string>{3341,"Fe54"},
	std::pair<int,std::string>{3348,"Mn54"},
	std::pair<int,std::string>{3342,"Mn55"},
	std::pair<int,std::string>{3352,"Mn56"},
	std::pair<int,std::string>{3343,"Fe56"},
	std::pair<int,std::string>{3344,"Fe57"},
	std::pair<int,std::string>{3347,"Fe58"},
	std::pair<int,std::string>{3353,"Eu154"},
	std::pair<int,std::string>{3336,"Gd158"},
	std::pair<int,std::string>{3337,"Gd156"},
	std::pair<int,std::string>{3338,"Gd157"},
	std::pair<int,std::string>{3339,"Gd155"},
};
