name: ToolAnalysis C/C++ CI

on:
  push:
    branches: [ Application ]
  pull_request:
    branches: [ Application ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

   build_1:
    runs-on: ubuntu-latest
    #container: 'anniesoft/toolanalysis:latest'
    steps:
      - name: Check disk space
        run: |
          sudo dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -nr | head
          df . -h
          sudo du / -hx -d 4 --threshold=1G | sort -hr | head
      - name: Free disk space
        run: |
          # https://github.com/actions/virtual-environments/issues/2840
          # https://stackoverflow.com/questions/75536771/github-runner-out-of-disk-space-after-building-docker-image
          sudo rm -rf \
            /usr/share/dotnet /usr/local/lib/android /opt/ghc \
            /usr/local/share/powershell /usr/share/swift /usr/local/.ghcup \
            /usr/lib/jvm /usr/local/share/boost
          sudo rm -rf "$AGENT_TOOLSDIRECTORY";
          echo "some directories deleted"
          sudo apt-get update --allow-releaseinfo-change
          echo "apt-get update: $?"
          sudo apt install aptitude -y >/dev/null
          echo "aptitude install: $?"
          sudo aptitude purge aria2 -f -y  >/dev/null || true
          sudo aptitude purge ansible -f -y  >/dev/null || true
          sudo aptitude purge azure-cli -f -y  >/dev/null || true
          sudo aptitude purge shellcheck -f -y  >/dev/null || true
          sudo aptitude purge rpm -f -y  >/dev/null || true
          sudo aptitude purge xorriso -f -y  >/dev/null || true
          sudo aptitude purge zsync -f -y  >/dev/null || true
          sudo aptitude purge esl-erlang -f -y  >/dev/null || true
          sudo aptitude purge firefox -f -y  >/dev/null || true
          sudo aptitude purge gfortran-8 -f -y  >/dev/null || true
          sudo aptitude purge gfortran-9 -f -y  >/dev/null || true
          sudo aptitude purge google-chrome-stable -f -y  >/dev/null || true
          sudo aptitude purge google-cloud-sdk -f -y  >/dev/null || true
          sudo aptitude purge google-cloud-cli -f -y  >/dev/null || true
          sudo aptitude purge imagemagick -f -y  >/dev/null || true
          sudo aptitude purge libmagickcore-dev -f -y  >/dev/null || true
          sudo aptitude purge libmagickwand-dev -f -y  >/dev/null || true
          sudo aptitude purge libmagic-dev -f -y  >/dev/null || true
          sudo aptitude purge ant -f -y  >/dev/null || true
          sudo aptitude purge ant-optional -f -y  >/dev/null || true
          sudo aptitude purge kubectl -f -y  >/dev/null || true
          sudo aptitude purge mercurial -f -y  >/dev/null || true
          sudo aptitude purge apt-transport-https -f -y  >/dev/null || true
          sudo aptitude purge mono-complete -f -y  >/dev/null || true
          sudo aptitude purge libmysqlclient -f -y  >/dev/null || true
          sudo aptitude purge unixodbc-dev -f -y  >/dev/null || true
          sudo aptitude purge yarn -f -y  >/dev/null || true
          sudo aptitude purge chrpath -f -y  >/dev/null || true
          sudo aptitude purge libssl-dev -f -y  >/dev/null || true
          sudo aptitude purge libxft-dev -f -y  >/dev/null || true
          sudo aptitude purge libfreetype6 -f -y  >/dev/null || true
          sudo aptitude purge libfreetype6-dev -f -y  >/dev/null || true
          sudo aptitude purge libfontconfig1 -f -y  >/dev/null || true
          sudo aptitude purge libfontconfig1-dev -f -y  >/dev/null || true
          sudo aptitude purge snmp -f -y  >/dev/null || true
          sudo aptitude purge pollinate -f -y  >/dev/null || true
          sudo aptitude purge libpq-dev -f -y  >/dev/null || true
          sudo aptitude purge postgresql-client -f -y  >/dev/null || true
          sudo aptitude purge powershell -f -y  >/dev/null || true
          sudo aptitude purge ruby -full -f -y  >/dev/null || true
          sudo aptitude purge sphinxsearch -f -y  >/dev/null || true
          sudo aptitude purge subversion -f -y  >/dev/null || true
          sudo aptitude purge mongodb-org -f -y  >/dev/null || true
          sudo aptitude purge azure-cli -f -y  >/dev/null || true
          sudo aptitude purge microsoft-edge-stable -f -y  >/dev/null || true
          sudo aptitude purge '~n ^mysql' -f -y >/dev/null || true
          sudo aptitude purge '~n ^php' -f -y >/dev/null || true
          sudo aptitude purge '~n ^dotnet' -f -y >/dev/null || true
          sudo aptitude purge '~n ^temurin' -f -y >/dev/null || true
          echo "some packages purged"
          sudo apt-get autoremove -y >/dev/null
          sudo apt-get autoclean -y >/dev/null
          echo "done apt autoremove and autoclean"
          sudo rm -rf /opt/microsoft                #   783M
          sudo rm -rf /usr/lib/llvm-*               #  1900M
          sudo rm -rf /usr/local/julia*             #  1008M
          sudo rm -rf /usr/local/share/chromium     #   613M
          sudo rm -rf /usr/local/share/powershell   #  1244M
          sudo rm -rf /usr/share/swift              #  3207M
          sudo df -TBG /
          echo "more directories deleted"
          #docker rmi $(docker image ls -aq) || true
          sudo swapoff /swapfile || true
          sudo rm -rf /swapfile
          echo "cleanup done"
      - name: Check disk space
        run: |
          sudo dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -nr | head
          df . -h
          sudo du / -hx -d 4 --threshold=1G | sort -hr | head
      
      - name: checkout
        uses: actions/checkout@v2
      
      ##################
      
      #- name: prerequisites
      #  run: yum install -y git make gcc-c++ which wget
      
      #- name: build
      #  run: 
      #  echo `pwd` && ln -s /ToolAnalysis/ToolDAQ $PWD/ToolDAQ && ls -l && ls -l ./ToolDAQ && source ./Setup.sh && make clean && make
      
      ##################
      
      #- name: test
      #  run : source ./Setup.sh && ./Analyse
      
      #- name: build and test
      #  uses: docker://anniesoft/toolanalysis:latest
      #  with:
      #    entrypoint: /bin/bash
      #    args: -c "echo `pwd` && ln -s /ToolAnalysis/ToolDAQ $PWD/ToolDAQ && ls -l && ls -l ./ToolDAQ && source ./Setup.sh && make clean && make && ./Analyse"
      
      ##################
      
      - name: build and test 
        uses: Baardrw/docker-run-action@v4
        with:
          image: anniesoft/toolanalysis:latest
          registry: docker.io
          options: -v ${{ github.workspace }}:/TA
          run: |
            echo "Running Script"
            echo `pwd`
            ls -l
            cd /TA
            git config --global --add safe.directory /TA
            ls -l
            ln -s /ToolAnalysis/ToolDAQ $PWD/ToolDAQ
            ls -l ./ToolDAQ
            source ./Setup.sh
            make clean
            make
            ./Analyse
            
      

